"""Shared paths and rules. Every measurement reads the same staged file set, so line counts,
complexity and the page all describe exactly the same code."""
import json
import re
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES_DIR = ROOT / '.sources'
STAGE = ROOT / '.stage'
DATA = ROOT / 'data'
CLOC = ROOT / 'node_modules/.bin/cloc'
CONFIG = json.loads((ROOT / 'sources.json').read_text())
WALLETS = list(CONFIG['wallets'])

# Programming languages only: no JSON, XML, Markdown, assets or build scripts.
LANGS = ['Swift', 'Kotlin', 'Objective-C', 'Objective-C++', 'C', 'C++', 'C/C++ Header',
         'TypeScript', 'JavaScript', 'JSX', 'Dart', 'Go', 'Rust']
EXTENSIONS = {'.swift', '.kt', '.m', '.mm', '.c', '.cc', '.cpp', '.h', '.hpp', '.ts', '.tsx', '.js',
              '.jsx', '.dart', '.go', '.rs'}
# Tests, other platforms, vendored trees and tooling never build into the iPhone app.
SKIP_DIRS = {'test', 'tests', '__tests__', '__mocks__', 'e2e', 'integration_test', 'itest', 'lntest', 'fuzz',
             'bench', 'benches', 'testdata', 'Tests', 'node_modules', 'Pods', 'android', 'docs', '.github'}
TEST_FILE = re.compile(
    r'(_test\.go|\.test\.[jt]sx?|\.spec\.[jt]sx?|Tests?\.(swift|kt|m)|_test\.dart|'
    r'(^|/|_)tests?\.rs|test_utils\.rs|functional_test_utils\.rs|'
    r'\.pb\.go|\.pb\.gw\.go|\.pb\.json\.go|_grpc\.pb\.go|\.pb\.swift|_pb\.[jt]s|\.pb\.(dart|m|h))$')
TEST_PATH = re.compile(r'/(commonTest|jvmTest|nativeTest|linuxTest|iosTest|androidTest|androidMain|'
                       r'jvmMain|linuxMain|[A-Za-z]*Tests|[A-Za-z]*UITests|test_utils)/')
GENERATED = re.compile(r'Code generated .* DO NOT EDIT|@generated|automatically generated|autogenerated|'
                       r'generated by (uniffi|protoc|sqlc|swift-protobuf)|This file was generated', re.I)


def source_dir(key):
    return SOURCES_DIR / key


def resolve(ref):
    """'phoenix:phoenix-ios/phoenix-ios' -> the checked-out path."""
    key, _, path = ref.partition(':')
    return source_dir(key) / path


def write_json(path, value):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=1, sort_keys=False, ensure_ascii=False) + '\n')


def strip_rust_tests(text):
    """Remove #[cfg(test)] / #[cfg(all(test, ...))] modules, which Rust keeps inside source files."""
    out, i = [], 0
    attr = re.compile(r'#\[cfg\((?:all\()?test\b[^\]]*\]\s*(?:pub(?:\([^)]*\))?\s+)?mod\s+\w+\s*\{')
    while True:
        m = attr.search(text, i)
        if not m:
            out.append(text[i:])
            return ''.join(out)
        out.append(text[i:m.start()])
        j, depth = m.end(), 1
        while depth and j < len(text):
            c = text[j]
            if text.startswith('//', j):
                j = text.find('\n', j)
                j = len(text) if j < 0 else j
                continue
            if text.startswith('/*', j):
                j = text.find('*/', j) + 2
                continue
            r = re.match(r'r(#*)"', text[j:j + 8]) if c == 'r' and not text[j - 1].isalnum() else None
            if r:
                close = '"' + r.group(1)
                j = text.find(close, j + len(r.group(0))) + len(close)
                continue
            if c == '"':
                j += 1
                while text[j] != '"':
                    j += 2 if text[j] == '\\' else 1
                j += 1
                continue
            ch = re.match(r"'(?:\\.|[^\\'])'|b'(?:\\.|[^\\'])'", text[j:j + 12])
            if ch:
                j += len(ch.group(0))
                continue
            depth += c == '{'
            depth -= c == '}'
            j += 1
        i = j


def counted_files(refs):
    """The files a part of a wallet ships: programming-language sources that build into the
    iPhone app, minus tests, other platforms and generated files. Returns (kept, generated)."""
    kept, generated = [], []
    for ref in refs:
        src = resolve(ref)
        files = [src] if src.is_file() else sorted(f for f in src.rglob('*') if f.is_file())
        for f in files:
            rel = str(f.relative_to(SOURCES_DIR))
            if f.suffix not in EXTENSIONS or SKIP_DIRS & set(f.relative_to(SOURCES_DIR).parts[:-1]):
                continue
            if TEST_FILE.search(rel) or TEST_PATH.search('/' + rel):
                continue
            if GENERATED.search(f.read_text(errors='ignore')[:1500]):
                generated.append(rel)
                continue
            kept.append(f)
    return kept, generated


def stage(refs):
    """Copy a part's counted files into .stage/ (Rust inline tests removed) and return them."""
    shutil.rmtree(STAGE, ignore_errors=True)
    kept, generated = counted_files(refs)
    staged = []
    for f in kept:
        text = f.read_text(errors='ignore')
        if f.suffix == '.rs':
            text = strip_rust_tests(text)
        dest = STAGE / f.relative_to(SOURCES_DIR)
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(text)
        staged.append(dest)
    return staged, generated


def cloc(args, cwd=ROOT, input_text=None):
    return subprocess.run([str(CLOC), '--quiet', '--timeout', '0', '--skip-uniqueness'] + args,
                          cwd=cwd, input=input_text, capture_output=True, text=True, check=True).stdout
